import { useState } from 'react'
import { Check, Plus } from 'lucide-react'
import type { View, GovernanceConfig } from '@/src/aegis/view-types'
import { emptyGovernance, governanceModules } from '@/src/aegis/view-types'
import { Button } from './shared'

export function RegisterView({ onNavigate }: { onNavigate: (view: View) => void }) { const [name, setName] = useState(''); const [context, setContext] = useState(''); const [registered, setRegistered] = useState(false); const [governance, setGovernance] = useState<GovernanceConfig>(emptyGovernance); const toggle = (key: keyof GovernanceConfig) => setGovernance((current) => ({ ...current, [key]: !current[key] }))
 if (registered) return <div className="success-panel"><div className="success-icon"><Check size={24} /></div><span className="section-kicker text-emerald-300">Registration complete</span><h2>{name || 'New Agent'} is now registered</h2><p>Its context and selected governance modules are ready for runtime use.</p><Button onClick={() => onNavigate('agents')}>View registered agents</Button></div>
 return <div className="form-page"><div className="page-intro"><div><span className="section-kicker">New runtime connection</span><h2>Register an agent</h2><p>Define this agent&apos;s identity, context, and governance modules.</p></div></div><div className="form-panel"><div className="form-grid"><label>Agent name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Customer Research Agent" /></label><label>Agent endpoint<input placeholder="https://agent.example.com" /></label><label className="wide">Description<textarea rows={3} placeholder="What does this agent do?" /></label><label>Owner / team<input placeholder="Operations team" /></label><label>Autonomy level<select><option>Level 2 · Assisted</option><option>Level 3 · Conditional</option><option>Level 4 · Autonomous</option></select></label><label className="wide">Agent-specific context<textarea value={context} onChange={(e) => setContext(e.target.value)} rows={4} placeholder="Describe this agent&apos;s purpose, data boundaries, approved behaviors, and special instructions." /><small>This context belongs only to this agent and is used as governance evidence.</small></label></div><div className="form-divider"><span className="section-kicker">Choose governance modules</span><p>Nothing is enabled by default. Select only the controls this agent needs.</p><div className="governance-grid">{governanceModules.map(([key, label, text]) => <button type="button" key={key} onClick={() => toggle(key)} className={`governance-option ${governance[key] ? 'selected' : ''}`}><span className="check-box">{governance[key] && <Check size={13} />}</span><span><b>{label}</b><small>{text}</small></span></button>)}</div></div><Button disabled={!name.trim()} onClick={() => setRegistered(true)}><Plus size={14} /> Register agent</Button></div></div> }
